name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Update the config
      run: echo "export const settings = {host:\"https://library-m2d4.onrender.com\"}" > src/config.js
    - name: Start backend
      run: npm run start:be &
    - name: Start frontend
      run: npm run start:fe &
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Execute the UI tests
      run: npm run test:ui

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with: 
            service_id: ${{ secrets.RENDER_SERVICE_BE_ID}}
            api_key: ${{ secrets.RENDER_API_KEY}}
            wait_deploy: true

  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with: 
            service_id: ${{ secrets.RENDER_SERVICE_FE_ID}}
            api_key: ${{ secrets.RENDER_API_KEY}}
            wait_deploy: true

